apiVersion: apps/v1
kind: Service

metadata:
  name: {{ .Values.appserver.name }}-clusterip-service

spec:
  type: {{ .Values.appserver.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.appserver.image.exposedPort }}

  selector:
    server: {{ .Values.appserver.name }}
