apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.nginx.name }}-deployment

spec:
  replicas: {{ .Values.nginx.replicas }}

  selector:
    matchlabels:
      server: {{ .Values.nginx.name }}

  template:
    metadata:
      labels:
        server: {{ .Values.nginx.name }}
    spec:
      container:
       - name: {{ .Values.nginx.name }}
          image: {{ .Values.nginx.image }}:{{ .Values.nginx.image.tag }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.nginx.image.exposedPort }}
